In [ ]:
import numpy as np

In [ ]:
vetor = [2, 6, 8, 10]
type(vetor)

list

In [ ]:
matriz = [[1, 2, 3], 
          [4, 5, 6], 
          [7, 8, 9]]
type(matriz)
print(matriz)   

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [7]:
vetor = np.array([1, 2, 3, 6])

In [9]:
type(vetor)
print(vetor)

[1 2 3 6]


In [11]:
matriz = np.ones((2, 3))
matriz

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
matriz_diag = np.diag((1, 2, 3, 10, 910, 92, 83, 1), k=0) # k=0 main diagonal, k>0 above, k<0 below
matriz_diag

array([[  1,   0,   0,   0,   0,   0,   0,   0],
       [  0,   2,   0,   0,   0,   0,   0,   0],
       [  0,   0,   3,   0,   0,   0,   0,   0],
       [  0,   0,   0,  10,   0,   0,   0,   0],
       [  0,   0,   0,   0, 910,   0,   0,   0],
       [  0,   0,   0,   0,   0,  92,   0,   0],
       [  0,   0,   0,   0,   0,   0,  83,   0],
       [  0,   0,   0,   0,   0,   0,   0,   1]])